### ISSUE TITLE
Updates needed;

### ISSUE THREAD

**Issue by ShadedJon** [DevotedMC/CivChat2#1]
1. We need a way to enable [prefixes] in Pex for Civchat.

**Comment by ShadedJon** [comment]
1. Adding better /ignore functionality.

**Comment by ProgrammerDan** [comment]
Just make these separate top-level issues, so we can assign them.

**Comment by ProgrammerDan** [comment]
/ignore can apply to all chat now, and apply to groups. Prefixes enabled through change here and PEXPrefix. Ranged chat colors added recently.
